// Shared mapping of skill labels to icon sources, used by both the Skills
// tab and the "tech stack as friends" avatar bubbles in the profile header.

// Maps a skill label to its local icon slug under /public/tech/<slug>.svg.
// (Generated by scripts/extract-tech-icons.mjs from the tech-stack-icons set.)
export const SKILL_TO_ICON: Record<string, string> = {
  // Frontend
  React: "react",
  "Next.js": "nextjs",
  "Tailwind CSS": "tailwindcss",
  "shadcn/ui": "shadcnui",
  "Framer Motion": "framer",
  HTML5: "html5",
  CSS3: "css3",
  Figma: "figma",
  // Languages
  TypeScript: "typescript",
  JavaScript: "js",
  Python: "python",
  Bash: "bash",
  // Backend
  "Node.js": "nodejs",
  Express: "expressjs",
  NestJS: "nestjs",
  Django: "django",
  PHP: "php",
  Prisma: "prisma",
  Drizzle: "drizzle",
  // Databases
  PostgreSQL: "postgresql",
  MongoDB: "mongodb",
  Supabase: "supabase",
  Firebase: "firebase",
  Redis: "redis",
  SQLite: "sqlite",
  // Cloud & Infra
  AWS: "aws",
  "Google Cloud Platform": "gcloud",
  CloudFlare: "cloudflare",
  Vercel: "vercel",
  Docker: "docker",
  Netlify: "netlify",
  Railway: "railway",
  Nginx: "nginx",
  "Digital Ocean": "digitalocean",
  // AI / ML
  OpenAI: "openai",
  Claude: "claude",
  Anthropic: "anthropic",
  LangChain: "langchain",
  "Hugging Face": "huggingface",
  Ollama: "ollama",
  Gemini: "gemini",
  LlamaIndex: "llamaindex",
  // Automation
  n8n: "n8n",
  Zapier: "zapier",
  "Make.com": "make",
  Airtable: "airtable",
  "Node-RED": "nodered",
  // Dev Tools
  Git: "git",
  GitHub: "github",
  Postman: "postman",
  Jest: "jest",
  Playwright: "playwright",
  ESLint: "eslint",
  pnpm: "pnpm",
};

// Maps a skill label to a custom image in /public for icons not available in tech-stack-icons.
export const SKILL_TO_IMAGE: Record<string, string> = {
  GoHighLevel: "/skills/gohighlevel.png",
};

// Curated, recognizable skills shown as overlapping avatar bubbles ("friends")
// in the profile header. Order matters — these render left to right.
export const FEATURED_TECH = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Python",
  "Tailwind CSS",
  "OpenAI",
  "Claude",
  "Docker",
  "AWS",
] as const;
