// Shared mapping of skill labels to icon sources, used by both the Skills
// tab and the "tech stack as friends" avatar bubbles in the profile header.

// Maps a skill label to its local icon slug under /public/tech/<slug>.svg.
// (Generated by scripts/extract-tech-icons.mjs from the tech-stack-icons set.)
export const SKILL_TO_ICON: Record<string, string> = {
  // Frontend
  React: "react",
  "Next.js": "nextjs",
  "Tailwind CSS": "tailwindcss",
  "shadcn/ui": "shadcnui",
  "Framer Motion": "framer",
  HTML5: "html5",
  CSS3: "css3",
  Figma: "figma",
  // Languages
  TypeScript: "typescript",
  JavaScript: "js",
  Python: "python",
  Bash: "bash",
  // Backend
  "Node.js": "nodejs",
  Express: "expressjs",
  NestJS: "nestjs",
  Django: "django",
  PHP: "php",
  Prisma: "prisma",
  Drizzle: "drizzle",
  // Databases
  PostgreSQL: "postgresql",
  MongoDB: "mongodb",
  Supabase: "supabase",
  Firebase: "firebase",
  Redis: "redis",
  SQLite: "sqlite",
  // Cloud & Infra
  AWS: "aws",
  "Google Cloud Platform": "gcloud",
  CloudFlare: "cloudflare",
  Vercel: "vercel",
  Docker: "docker",
  Netlify: "netlify",
  Railway: "railway",
  Nginx: "nginx",
  "Digital Ocean": "digitalocean",
  // AI / ML
  OpenAI: "openai",
  Claude: "claude",
  Anthropic: "anthropic",
  LangChain: "langchain",
  "Hugging Face": "huggingface",
  Ollama: "ollama",
  Gemini: "gemini",
  LlamaIndex: "llamaindex",
  // Automation
  n8n: "n8n",
  Zapier: "zapier",
  "Make.com": "make",
  Airtable: "airtable",
  "Node-RED": "nodered",
  // Dev Tools
  Git: "git",
  GitHub: "github",
  Postman: "postman",
  Jest: "jest",
  Playwright: "playwright",
  ESLint: "eslint",
  pnpm: "pnpm",
  Cursor: "cursor",
  "VS Code": "vscode",
  Replit: "replit",
};

// Maps a skill label to a custom image in /public for icons not available in tech-stack-icons.
export const SKILL_TO_IMAGE: Record<string, string> = {
  GoHighLevel: "/skills/gohighlevel.png",
  Base44: "/skills/base44.png",
};

// Maps an AutomationProject tag (src/data/automation-projects.ts) to its logo
// slug under /public/tech/<slug>.svg. Only brand/tool tags are listed; concept
// tags (Workflows, Funnels, SMS Automation, Custom Fields, …) are intentionally
// omitted so they render as plain text chips. GoHighLevel is resolved via
// SKILL_TO_IMAGE in automationToolIcon() below.
//
// Slugs marked "sourced" are full-color logos that are NOT in the
// tech-stack-icons package and so are not produced by
// scripts/extract-tech-icons.mjs — they were downloaded once into /public/tech.
// See the README "Tech icons" section.
export const AUTOMATION_TOOL_TO_ICON: Record<string, string> = {
  Slack: "slack",
  Zapier: "zapier",
  n8n: "n8n",
  OpenAI: "openai",
  Trello: "trello",
  Airtable: "airtable",
  Asana: "asana",
  Javascript: "js",
  "Gemini 2.5 Flash": "gemini",
  // sourced full-color SVGs (not from tech-stack-icons)
  Gmail: "gmail",
  "Google Sheets": "googlesheets",
  "Google Calendar": "googlecalendar",
  "Google Drive": "googledrive",
  Shopify: "shopify",
};

// Resolve an automation tag to a renderable icon: a bundled/sourced SVG slug
// (render with <TechIcon>) or a custom raster image (render with next/image).
// Returns null for concept tags that have no logo, so callers fall back to text.
export function automationToolIcon(
  tag: string,
): { slug: string } | { image: string } | null {
  const slug = AUTOMATION_TOOL_TO_ICON[tag];
  if (slug) return { slug };
  const image = SKILL_TO_IMAGE[tag]; // GoHighLevel
  if (image) return { image };
  return null;
}

// Curated, recognizable skills shown as overlapping avatar bubbles ("friends")
// in the profile header. Order matters — these render left to right.
export const FEATURED_TECH = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Python",
  "Tailwind CSS",
  "OpenAI",
  "Claude",
  "Docker",
  "AWS",
] as const;
